-- INSERT INTO USERS --
insert into users (name, last_name, email, phone) values ('Opal', 'Niles', 'oniles0@wiley.com', '337-316-3658');
insert into users (name, last_name, email, phone) values ('Morrie', 'Bradbrook', 'mbradbrook1@freewebs.com', '662-707-1786');
insert into users (name, last_name, email, phone) values ('Ikey', 'Local', 'ilocal2@google.co.jp', '863-898-0766');
insert into users (name, last_name, email, phone) values ('Tiebout', 'Baudic', 'tbaudic3@nyu.edu', '768-527-6805');
insert into users (name, last_name, email, phone) values ('Jaclyn', 'MacClure', 'jmacclure4@stumbleupon.com', '634-997-4361');
insert into users (name, last_name, email, phone) values ('Torrey', 'Dobbings', 'tdobbings5@mozilla.org', '523-536-3030');
insert into users (name, last_name, email, phone) values ('Tiebout', 'Lowles', 'tlowles6@cyberchimps.com', '537-577-2985');
insert into users (name, last_name, email, phone) values ('Tades', 'Whitwood', 'twhitwood7@typepad.com', '472-462-7336');
insert into users (name, last_name, email, phone) values ('Kelsey', 'Wolffers', 'kwolffers8@fotki.com', '124-904-0618');
insert into users (name, last_name, email, phone) values ('Heddie', 'Ings', 'hings9@wiley.com', '895-365-8459');
insert into users (name, last_name, email, phone) values ('Della', 'Bozier', 'dboziera@domainmarket.com', '260-744-3178');
insert into users (name, last_name, email, phone) values ('Duane', 'Kyttor', 'dkyttorb@oracle.com', '259-583-5461');
insert into users (name, last_name, email, phone) values ('Susann', 'Fernez', 'sfernezc@cnet.com', '196-182-8006');
insert into users (name, last_name, email, phone) values ('Aeriel', 'Heel', 'aheeld@elegantthemes.com', '715-830-4477');
insert into users (name, last_name, email, phone) values ('Roseanna', 'Bariball', 'rbariballe@xing.com', '888-122-0639');
insert into users (name, last_name, email, phone) values ('Bern', 'Buglass', 'bbuglassf@gmpg.org', '514-250-1655');
insert into users (name, last_name, email, phone) values ('Allan', 'Ferrant', 'aferrantg@unicef.org', '868-575-3471');
insert into users (name, last_name, email, phone) values ('Delphinia', 'Lesper', 'dlesperh@ihg.com', '573-440-9890');
insert into users (name, last_name, email, phone) values ('Clarita', 'Mowsdell', 'cmowsdelli@wufoo.com', '477-685-9509');
insert into users (name, last_name, email, phone) values ('Beauregard', 'Lippini', 'blippinij@admin.ch', '995-840-1933');
insert into users (name, last_name, email, phone) values ('Gwyn', 'Leipelt', 'gleipeltk@europa.eu', '602-384-7525');
insert into users (name, last_name, email, phone) values ('Oliver', 'Cuncliffe', 'ocuncliffel@infoseek.co.jp', '865-941-9682');
insert into users (name, last_name, email, phone) values ('Huey', 'Blaskett', 'hblaskettm@smh.com.au', '318-477-7212');
insert into users (name, last_name, email, phone) values ('Jocelyne', 'Jaouen', 'jjaouenn@livejournal.com', '985-896-2550');
insert into users (name, last_name, email, phone) values ('Ogden', 'Burstowe', 'oburstoweo@jalbum.net', '631-536-2025');
insert into users (name, last_name, email, phone) values ('Omar', 'Statersfield', 'ostatersfieldp@theguardian.com', '555-970-4334');
insert into users (name, last_name, email, phone) values ('Thurstan', 'Schult', 'tschultq@etsy.com', '767-572-9090');
insert into users (name, last_name, email, phone) values ('Heather', 'Bouldon', 'hbouldonr@blog.com', '123-434-0820');
insert into users (name, last_name, email, phone) values ('Brandy', 'Cushion', 'bcushions@foxnews.com', '374-294-6007');
insert into users (name, last_name, email, phone) values ('Coop', 'Shearman', 'cshearmant@si.edu', '537-204-3660');
insert into users (name, last_name, email, phone) values ('De witt', 'Hintze', 'dhintzeu@cdbaby.com', '204-320-0241');
insert into users (name, last_name, email, phone) values ('Rorie', 'Klimaszewski', 'rklimaszewskiv@google.pl', '861-260-7819');
insert into users (name, last_name, email, phone) values ('Jarrad', 'McGilvray', 'jmcgilvrayw@harvard.edu', '728-127-2221');
insert into users (name, last_name, email, phone) values ('Harbert', 'Nannini', 'hnanninix@nbcnews.com', '603-240-7495');
insert into users (name, last_name, email, phone) values ('Lowe', 'Peppard', 'lpeppardy@rakuten.co.jp', '281-308-8541');
insert into users (name, last_name, email, phone) values ('Michale', 'Shoebridge', 'mshoebridgez@newsvine.com', '441-934-4495');
insert into users (name, last_name, email, phone) values ('Cammie', 'Metheringham', 'cmetheringham10@paypal.com', '256-127-5411');
insert into users (name, last_name, email, phone) values ('Curtis', 'Hardy-Piggin', 'chardypiggin11@usa.gov', '742-158-7677');
insert into users (name, last_name, email, phone) values ('Emile', 'Moral', 'emoral12@mashable.com', '102-544-3107');
insert into users (name, last_name, email, phone) values ('Ashlee', 'Creaney', 'acreaney13@shareasale.com', '265-918-5529');
insert into users (name, last_name, email, phone) values ('Claybourne', 'Sinton', 'csinton14@networkadvertising.org', '353-951-8814');
insert into users (name, last_name, email, phone) values ('Tally', 'Snartt', 'tsnartt15@uol.com.br', '971-714-8224');
insert into users (name, last_name, email, phone) values ('Luisa', 'Carnall', 'lcarnall16@rediff.com', '459-601-4625');
insert into users (name, last_name, email, phone) values ('Gherardo', 'Lello', 'glello17@bbc.co.uk', '229-687-9895');
insert into users (name, last_name, email, phone) values ('Alvinia', 'Crudge', 'acrudge18@reddit.com', '422-800-0389');
insert into users (name, last_name, email, phone) values ('Cross', 'Jose', 'cjose19@bing.com', '195-668-1180');
insert into users (name, last_name, email, phone) values ('Rozanne', 'Wybrow', 'rwybrow1a@ovh.net', '378-452-5689');
insert into users (name, last_name, email, phone) values ('Claudius', 'Aldwinckle', 'caldwinckle1b@canalblog.com', '356-947-8736');
insert into users (name, last_name, email, phone) values ('Byram', 'Marshall', 'bmarshall1c@nasa.gov', '269-333-8336');
insert into users (name, last_name, email, phone) values ('Kelley', 'Hardwicke', 'khardwicke1d@ucoz.ru', '478-812-1067');

-- INSERT INTO PRODUCTS --
insert into products (name, price, expiration_date) values ('Cranberries - Frozen', 812.7, '2013-09-29');
insert into products (name, price, expiration_date) values ('Hummus - Spread', 287.14, '2027-01-19');
insert into products (name, price, expiration_date) values ('Soup - Campbells Broccoli', 531.09, '2029-04-14');
insert into products (name, price, expiration_date) values ('Wine - White, Ej', 343.74, '2028-06-19');
insert into products (name, price, expiration_date) values ('Sour Puss - Tangerine', 791.43, null);
insert into products (name, price, expiration_date) values ('Veal - Insides, Grains', 127.05, '2018-11-05');
insert into products (name, price, expiration_date) values ('Tomato - Tricolor Cherry', 554.2, '2022-08-01');
insert into products (name, price, expiration_date) values ('Breakfast Quesadillas', 742.73, '2023-08-15');
insert into products (name, price, expiration_date) values ('Rum - Mount Gay Eclipes', 131.44, '2025-07-28');
insert into products (name, price, expiration_date) values ('Tea - Decaf Lipton', 21.56, '2024-11-16');
insert into products (name, price, expiration_date) values ('Pasta - Ravioli', 656.57, '2014-12-29');
insert into products (name, price, expiration_date) values ('Chocolate - Chips Compound', 688.75, '2022-12-19');
insert into products (name, price, expiration_date) values ('Bread Base - Italian', 258.42, '2028-01-22');
insert into products (name, price, expiration_date) values ('Ranchero - Primerba, Paste', 988.99, null);
insert into products (name, price, expiration_date) values ('Arctic Char - Fillets', 656.21, '2023-09-06');
insert into products (name, price, expiration_date) values ('Yeast - Fresh, Fleischman', 799.75, '2027-08-24');
insert into products (name, price, expiration_date) values ('Coffee - French Vanilla Frothy', 936.94, '2027-11-10');
insert into products (name, price, expiration_date) values ('Turkey - Breast, Double', 598.67, '2024-01-25');
insert into products (name, price, expiration_date) values ('Squash - Pepper', 805.23, '2023-10-10');
insert into products (name, price, expiration_date) values ('Turnip - Mini', 889.8, '2026-04-14');
insert into products (name, price, expiration_date) values ('Wine - Merlot Vina Carmen', 599.23, '2028-06-13');
insert into products (name, price, expiration_date) values ('Appetizer - Asian Shrimp Roll', 428.46, '2024-11-29');
insert into products (name, price, expiration_date) values ('Sauce - Hollandaise', 936.78, '2028-02-06');
insert into products (name, price, expiration_date) values ('Yogurt - Plain', 802.3, '2013-04-01');
insert into products (name, price, expiration_date) values ('Tea - Green', 373.35, '2028-01-29');
insert into products (name, price, expiration_date) values ('Cattail Hearts', 541.97, '2023-03-22');
insert into products (name, price, expiration_date) values ('Mushroom Morel Fresh', 460.98, '2017-05-22');
insert into products (name, price, expiration_date) values ('Jicama', 852.2, '2027-10-14');
insert into products (name, price, expiration_date) values ('Glass - Juice Clear 5oz 55005', 757.55, null);
insert into products (name, price, expiration_date) values ('Onions Granulated', 751.81, '2022-09-13');
insert into products (name, price, expiration_date) values ('Ecolab - Ster Bac', 710.68, '2028-12-13');
insert into products (name, price, expiration_date) values ('Energy Drink Red Bull', 249.51, '2027-03-08');
insert into products (name, price, expiration_date) values ('Flavouring - Raspberry', 510.47, '2029-02-07');
insert into products (name, price, expiration_date) values ('Artichoke - Bottom, Canned', 344.17, '2029-04-13');
insert into products (name, price, expiration_date) values ('Bar Mix - Lime', 392.35, '2024-01-11');
insert into products (name, price, expiration_date) values ('Sausage - Blood Pudding', 397.2, '2025-12-02');
insert into products (name, price, expiration_date) values ('The Pop Shoppe - Lime Rickey', 68.43, '2026-05-08');
insert into products (name, price, expiration_date) values ('Wine - Muscadet Sur Lie', 155.8, '2026-04-21');
insert into products (name, price, expiration_date) values ('Clam Nectar', 200.87, '2019-02-24');
insert into products (name, price, expiration_date) values ('Cornstarch', 37.24, '2025-01-07');
insert into products (name, price, expiration_date) values ('Beef - Tongue, Fresh', 519.87, '2023-11-09');
insert into products (name, price, expiration_date) values ('Cheese Cheddar Processed', 987.21, '2029-03-04');
insert into products (name, price, expiration_date) values ('Sea Bass - Fillets', 109.0, '2019-07-06');
insert into products (name, price, expiration_date) values ('Pate - Peppercorn', 451.94, '2027-11-11');
insert into products (name, price, expiration_date) values ('Venison - Ground', 808.67, '2026-10-04');
insert into products (name, price, expiration_date) values ('Lamb - Whole, Fresh', 414.51, '2023-05-31');
insert into products (name, price, expiration_date) values ('Pate - Liver', 720.98, '2028-10-05');
insert into products (name, price, expiration_date) values ('Kellogs All Bran Bars', 264.32, '2024-01-14');
insert into products (name, price, expiration_date) values ('Coffee Cup 8oz 5338cd', 834.11, '2029-03-11');
insert into products (name, price, expiration_date) values ('Butter - Unsalted', 970.66, '2016-08-22');

-- INSERT INTO PRODUCT_COMMENTS --
insert into product_comments (comment, comment_date, product_id, user_id) values ('Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', '2016-04-08', 35, 17);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Donec dapibus. Duis at velit eu est congue elementum.', '2019-02-16', 28, 50);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '2018-01-23', 5, 13);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', '2019-04-28', 46, 34);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Phasellus sit amet erat. Nulla tempus.', '2016-05-08', 13, 43);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2019-06-03', 47, 42);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '2020-12-24', 45, 17);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2021-12-19', 11, 50);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Cras pellentesque volutpat dui.', '2014-11-03', 3, 30);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', '2015-01-16', 46, 9);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Vivamus in felis eu sapien cursus vestibulum.', '2022-06-18', 36, 48);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '2016-02-04', 24, 2);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', '2022-05-04', 46, 4);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', '2019-10-20', 30, 46);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', '2018-04-23', 33, 39);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '2012-09-20', 33, 50);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2020-06-02', 7, 24);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2012-10-25', 4, 42);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2021-03-26', 44, 28);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2019-03-02', 8, 30);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2014-03-17', 35, 12);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '2020-12-04', 17, 20);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Aliquam non mauris.', '2012-12-04', 30, 1);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Vivamus tortor.', '2012-09-08', 34, 31);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Etiam faucibus cursus urna. Ut tellus.', '2019-05-10', 9, 9);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', '2018-05-27', 39, 21);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Phasellus id sapien in sapien iaculis congue.', '2015-09-03', 34, 50);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '2014-01-30', 7, 40);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '2019-01-09', 17, 17);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2022-01-27', 6, 34);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Suspendisse potenti.', '2018-12-14', 10, 41);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', '2019-04-24', 47, 3);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2019-06-01', 46, 15);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Nullam sit amet turpis elementum ligula vehicula consequat.', '2021-09-29', 24, 46);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', '2016-08-12', 11, 43);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', '2016-07-14', 12, 42);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '2019-03-04', 33, 31);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', '2021-04-25', 14, 31);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', '2017-09-11', 15, 7);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', '2019-10-03', 6, 2);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', '2021-09-12', 36, 1);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Proin risus. Praesent lectus.', '2019-09-26', 45, 4);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', '2016-11-27', 43, 26);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', '2019-03-04', 5, 3);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Integer a nibh.', '2020-01-11', 23, 7);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '2017-09-16', 1, 7);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', '2020-07-06', 9, 3);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2016-02-16', 49, 23);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.', '2022-02-12', 36, 10);
insert into product_comments (comment, comment_date, product_id, user_id) values ('Cras non velit nec nisi vulputate nonummy.', '2012-10-30', 28, 13);